### ISSUE TITLE
About realtime viewer

### ISSUE THREAD

**Issue by ywaison** [city-super/Octree-GS#10]
Thank you very much for providing such a great work, I would like to know how to check the real-time rendering results during training.
The following is a screenshot of my training in windows and the command line parameters. When SIBR remote gaussian viewer is opened, there is nothing in the interface. I urgently hope to get your help
command line:python train.py --eval -s data/data/sundial_rgb -r -1 --gpu 0 --fork 2 --ratio 1  --iterations 40000 --port 24000 -m outputs/data/horse_rgb/horse_rgb_try --appearance_dim 0  --visible_threshold 0.9  --base_layer -1 --dist2level round --update_ratio 0.2  --progressive --init_level -1 --dist_ratio 0.999 --levels -1  --extra_ratio 0.5 --extra_up 0.01
![}PBA`H` SH{(J4 D7K30}Y](https://github.com/city-super/Octree-GS/assets/138007686/a1967fd2-d0e5-41ab-98e1-1e3e5bf0ecbb)

**Comment by tongji-rkr** [comment]
We have not made any additional changes to the remote viewer, please follow the instructions provided in the 3D-GS repo(https://github.com/graphdeco-inria/gaussian-splatting).

**Comment by ywaison** [comment]
Thank you very much! I will try it again!

**Comment by luoww1992** [comment]
@ywaison 
i want to do the same, have you done ? if done, how to do ?

**Comment by cat-fish-yu** [comment]
> Thank you very much! I will try it again!非常感谢！我会再试一次！

Hi, have you solved this problem? I have the same one.
