### ISSUE TITLE
poor results on custom datasets

### ISSUE THREAD

**Issue by cv-lab-x** [city-super/Octree-GS#12]
hi, thanks for your great work, i have tested octree-gs on large custom indoor datasets with defualt configs（mip360 datasets scripts）, the result is poor than origin gs or scaffold-gs.
how to improve the quality of the results?
Looking forward to your reply, thanks. @tongji-rkr

**Comment by tongji-rkr** [comment]
Thank you for your interest in our work。
Please first check if your code is up to date, and if so show `output.log`.
