### ISSUE TITLE
Questions about SIBR_viewers browser display and source code

### ISSUE THREAD

**Issue by xdw-123** [city-super/Octree-GS#13]
Thanks to the author, I encountered two problems:
One is to download your public exe execution program, where the -s and -m parameters point to that path specifically. What I understand is that -s points to the colmap generated folder, and -m is the model generated by output. The picture below is what I ran. As a result, the model cannot be viewed
<img width="722" alt="微信图片_20240416151056" src="https://github.com/city-super/Octree-GS/assets/38170100/b4b55cc7-9876-4c8a-835d-c79fb210d1fa">

Second, when compiling the source code of SIBR_viewers, it was found that the CudaRasterizer::Rasterizer::visible_filter function did not seem to be uploaded to the public.

**Comment by tongji-rkr** [comment]
![image](https://github.com/city-super/Octree-GS/assets/93235593/a5f09476-de1e-4331-8fa1-163d549e6ea5)

**Comment by xdw-123** [comment]
Thank you for your reply. I found that there seems to be no color_mlp.pt, cov_mlp.pt, embedding_appearance.pt, and opacity_mlp.pt files in the generated model. I ran train_db.sh directly and downloaded the test data sets drjohnson and playroom. Are there any missing steps? Will the function mentioned above be made public?

**Comment by tongji-rkr** [comment]
We fix the second problem you raised. you can replace `diff-gaussian-rasterization` with https://github.com/tongji-rkr/diff-gaussian-rasterization

**Comment by tongji-rkr** [comment]
![image](https://github.com/city-super/Octree-GS/assets/93235593/cd7a876c-0322-4820-aa98-4fb4e856c0f5)

**Comment by tongji-rkr** [comment]
if you set `appearance_dim`>0, embedding_appearance.pt will appear.

**Comment by xdw-123** [comment]
Thank you for your reply. What parameters need to be modified for these files to come out?
![image](https://github.com/city-super/Octree-GS/assets/38170100/a98f60e4-6b46-47c8-96a5-5bf2c044e319)

**Comment by tongji-rkr** [comment]
Did these documents not appear after your training? Could you give me a screenshot.

**Comment by xdw-123** [comment]
![image](https://github.com/city-super/Octree-GS/assets/38170100/cead98ef-2987-419c-8333-479e3820d3d1)
![image](https://github.com/city-super/Octree-GS/assets/38170100/d4a159c0-70b9-4e24-b679-56dadc82ecab)

**Comment by xdw-123** [comment]
I was also quite puzzled after seeing your screenshot of the operation.

**Comment by tongji-rkr** [comment]
Your training is fine, you can find the required files in `point_cloud/iteration_40000`.
But I'm not sure if viewers will work on Linux, since I compiled it on Win11.

**Comment by tongji-rkr** [comment]
You need to **move** the files to get the structure shown above.

**Comment by tongji-rkr** [comment]
> ![image](https://private-user-images.githubusercontent.com/93235593/322747981-a5f09476-de1e-4331-8fa1-163d549e6ea5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTYxNzAsIm5iZiI6MTcxMzI1NTg3MCwicGF0aCI6Ii85MzIzNTU5My8zMjI3NDc5ODEtYTVmMDk0NzYtZGUxZS00MzMxLThmYTEtMTYzZDU0OWU2ZWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA4MjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NTJkNTcyYTQ2MzU5MmI3MmM5MzMzNjI3N2JhODhmZTAxNTg5NzhiZDMwZjNjOWM5YzIyMWJkNzdhOGVmOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-ShC_E8ZVE5ALPUCEY9ypwM2qE30yC0Fi0rmGmnIyo)

Please create a new directory and paste the content you want into it according to this structure

**Comment by tongji-rkr** [comment]
This may be a legacy issue for 'Scaffold–GS' viewers, which I will resolve as soon as possible

**Comment by xdw-123** [comment]
Thank you for your reply. It is indeed necessary to create a new document and reposition the file. I now see the model.

**Comment by tongji-rkr** [comment]
We update the viewers. The latest viewer can directly rendering without changing the file structure.

**Comment by tongji-rkr** [comment]
We update the viewers. The latest viewer can directly rendering without changing the file structure.
