### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by hecodeit** [city-super/Octree-GS#14]
Thanks for making the project open source.

I tested the trained files provided in the README. 
For example, Garden scene, 
the Octree-GS Viewer only has a frame rate of 20-30, 
whereas the original Inria Viewer and the trained .ply files have a frame rate of 60.

Also, what changes were made to the original Inria Viewer by the Octree-GS Viewer?

**Comment by tongji-rkr** [comment]
May I ask what GPU you are using? The results we tested on 3090 are good.

**Comment by hecodeit** [comment]
3060 laptop

**Comment by tongji-rkr** [comment]
Octree-GS contains more tensor operations, so I encourage you to test it on a more powerful GPU.
In addition, we use desktop, which ensures better heat dissipation

**Comment by hecodeit** [comment]
Could you explain the modifications that the Octree-GS Viewer made to the original Inria Viewer?

**Comment by tongji-rkr** [comment]
It mainly include three aspects. Firstly, we get the attributes of anchor from .ply file, and the attributes of Gaussian are obtained according to **MLP** inference. In addition, we add a **selection** strategy for anchors. Finally, we added more **patterns** as well as partial LOD level visualizations

**Comment by hecodeit** [comment]
Ok, thanks @tongji-rkr.

Will check diff and find out.
