### ISSUE TITLE
las file of matrix city

### ISSUE THREAD

**Issue by oungji212** [city-super/Octree-GS#15]
Thank you for your work. 
I was inspired with your work and so I'd like to run the code for Matrix City, but it seems that the las file is required. 
But there isn't such a file in the Matrix City dataset. Did you create it yourself? If so, would you be willing to provide it?

**Comment by tongji-rkr** [comment]
Initial point cloud : https://drive.google.com/file/d/1J5sGnKhtOdXpGY0SVt-2D_VmL5qdrIc5/view?usp=sharing
ckpt for MatrixCity : https://drive.google.com/file/d/1SBs7IjxHQghI5rJ7n9vi9umz4--FnSVY/view?usp=sharing
