### ISSUE TITLE
Spherical Harmonics setting

### ISSUE THREAD

**Issue by hecodeit** [city-super/Octree-GS#18]
Don't find way to setting spherical harmonics?

Another question: Did this project have plan to make a WebGL Viewer for online user?

**Comment by jianglh-WHU** [comment]
Hi! Thank you for your interest in our work.
1. Just like Scaffold-GS, we utilize an MLP to decode the color of neural gaussians, so there is no spheical harmonics.
2. Currently, we have no plans to develop an online WebGL viewer.
