### ISSUE TITLE
Trajectory for small city

### ISSUE THREAD

**Issue by DerKleineLi** [city-super/Octree-GS#19]
Hi, could you share the trajectories for small city in the paper? I'd like to train and evaluate following the same trajectories.
Thanks in advance!

**Comment by jianglh-WHU** [comment]
Of course! We release the 3 trajectories for small city in https://drive.google.com/drive/folders/1RqgVA6-2W2RImKQhrEYEWmWIuXsnxCST?usp=drive_link.
