### ISSUE TITLE
how sets parameter when python train.py finished , output model can achieve LOD3 or higher  ? 

### ISSUE THREAD

**Issue by goometasoft** [city-super/Octree-GS#2]
thank your Octree-GS , i like it very much !

how sets parameter when python train.py finished , 
output model can achieve LOD3 or higher ?  e.g. LOD4  LOD5 ...

https://city-super.github.io/octree-gs/
Visualization at different LODs

**Comment by tongji-rkr** [comment]
You can directly adjust the parameter `levels` and we set it to 4, so we get LOD0~3. But I recommend you adjust `dist_ratio` to increase the number of levels by increasing the range of distances, which will give you a more refined result but larger number of Gaussians.
