### ISSUE TITLE
About SfM of MatrixCity Dataset

### ISSUE THREAD

**Issue by VerseWei** [city-super/Octree-GS#25]
Nice work!
How can I obtain the SfM results of the MatrixCity dataset? Can I use colmap directly? This seems to take a few days, is there any trick?

**Comment by tongji-rkr** [comment]
Actually, we did not use COLMAP to extract point clouds, and the specific method is referred to #6.
Initial point cloud : https://drive.google.com/file/d/1J5sGnKhtOdXpGY0SVt-2D_VmL5qdrIc5/view?usp=sharing
ckpt for MatrixCity : https://drive.google.com/file/d/1SBs7IjxHQghI5rJ7n9vi9umz4--FnSVY/view?usp=sharing

**Comment by VerseWei** [comment]
Thank you for your reply. We also need to provide camera parameters during training. Is it provided in JSON file format in your project, just like the transformations.json in the MatrixCity public dataset? My current problem is that I want to train in my own large-scale scene, but Colmap seems to be unable to handle tens of thousands of images. Therefore, I am considering other 3D software such as PhotoScan, but now I need to convert it to the file format required by your project. I am not sure if it is sparse/o or JSON. @tongji-rkr

**Comment by jianglh-WHU** [comment]
Sorry for late reply, we'll provide the point cloud of the Matrixicity dataset later by fusing the RGB-D images. If you need the pose and point cloud data for large-scale scenes, you can use the COLMAP (just make sure to downsample the input images first). Alternatively, you can try using 3D reconstruction software like Reality Capture or Context Capture. I'd be happy to provide some scripts to help transform the file formats to JSON if that would be useful for your needs.

**Comment by VerseWei** [comment]
Ok，thanks.

**Comment by jianglh-WHU** [comment]
We have provided the ply files of MatrixCity in the `small_city_pointcloud` folder.
