### ISSUE TITLE
How to get the viewer of point cloud in project page?

### ISSUE THREAD

**Issue by Linkersem** [city-super/Octree-GS#27]
@tongji-rkr @jianglh-WHU Hi,I'd like to be able to see the point cloud in the viewer and the change in the number of points and fps, like in the project page, how should I do that?
![image](https://github.com/city-super/Octree-GS/assets/49711774/7071c396-6719-4171-9d79-4a19ce867190)

**Comment by tongji-rkr** [comment]
I will update the viewer later.

**Comment by Linkersem** [comment]
thx for your quick reply!!

**Comment by tongji-rkr** [comment]
This is supported by the latest version of viewer!
