### ISSUE TITLE
Rendering speed w.r.t. distance' and 'number of Gaussians w.r.t. distance' graphs

### ISSUE THREAD

**Issue by dangdang2222** [city-super/Octree-GS#28]
Thank you for your excellent research! 
I am very interested and would like to draw the 'rendering speed w.r.t. distance' and 'number of Gaussians w.r.t. distance' graphs from Fig. 1 in your paper using my own dataset. Is there any code or hint that I can refer to?"

**Comment by tongji-rkr** [comment]
Actually we don't draw it by coding. We convert our data to graphs in Google Sheets.
