### ISSUE TITLE
Failure of Octree viewer

### ISSUE THREAD

**Issue by samcao0416** [city-super/Octree-GS#3]
Tank you for your work! I tried your pre-built binary viewer with my train model. However, neither mip-nerf 360 nor my own data's result can be loaded into the pre-built binary. 

It showed:

[SIBR] --  INFOS  --:   Initialization of GLFW
[SIBR] --  INFOS  --:   OpenGL Version: 4.6.0 NVIDIA 537.70[major: 4, minor: 6]
[SIBR] --  INFOS  --:   Dataset type:
Number of input Images to read: 185
Number of Cameras set up: 185
LOADSFM: Try to open D:\\Octree-GS\\data\\mipnerf360\\garden/sparse/0/points3D.bin
Num 3D pts 138766
[SIBR] --  INFOS  --:   SfM Mesh 'D:\\NeuDim\\NeuDim_Lab\\Octree-GS\\data\\mipnerf360\\garden/sparse/0/points3d.bin successfully loaded.  (138766) vertices detected. Init GL ...
[SIBR] --  INFOS  --:   Init GL mesh complete
[SIBR] --  INFOS  --:   opacity_mlp : 0
[SIBR] --  INFOS  --:   cov_mlp : 0
[SIBR] --  INFOS  --:   color_mlp : 0
[SIBR] --  INFOS  --:   embedding_appearance : 0

And then the window shut down and the program killed itself. Any idea what's the problem?

**Comment by Sunnyhong0326** [comment]
You can follow the following directory structure to successfully run the viewer.
where color_mlp.pt, cov_mlp.pt, opacity_mlp.pt and point_cloud.ply are in the iteration_XXXXX folder.
![image](https://github.com/city-super/Octree-GS/assets/66857678/4f6f1774-b70e-4537-b578-16cb75aae1b3)

**Comment by samcao0416** [comment]
After the training, no color_mlp.pt, cov_mlp.pt nor opacity_mlp.pt can be found in the result folder in both experiments. I strickly follow the train command, why aren't them be saved😂

**Comment by samcao0416** [comment]
Oh I found the .pts. But after I copied them as the structure, it still doesn't work.
<img width="267" alt="截屏2024-04-02 20 37 51" src="https://github.com/city-super/Octree-GS/assets/134524527/c6ebf2c3-1203-42d6-8cd0-a0c50b723888">

**Comment by Sunnyhong0326** [comment]
What if you follow the directory structure below?
![image](https://github.com/city-super/Octree-GS/assets/66857678/1a4d2593-fa1e-43b0-8ce7-8b8ada4590b8)
Note that in the point_cloud directory, there is **only point_cloud.ply one file**

**Comment by luoww1992** [comment]
@samcao0416 
what is your cmd ?
