### ISSUE TITLE
About rendering transitions between different LODs ?

### ISSUE THREAD

**Issue by TSlus** [city-super/Octree-GS#31]
In the paper, you said `We use a piecewise linear interpolation for the rendered pixel values between adjacent levels`, but I do not find the detail code in your released code. I would appreciate if you tell me the location of this code : )

**Comment by tongji-rkr** [comment]
In the `progressive` branch of the `map_to_int_level` function in `gaussian_model.py`, and it is designed for continuous rendering.

**Comment by TSlus** [comment]
> In the `progressive` branch of the `map_to_int_level` function in `gaussian_model.py`, and it is designed for continuous rendering.

Yes, thank you, I find it. But I also find `map_to_int_level` function is mapping `pred_level` to integer level defined, there is not existing interpolating between adjacent levels. I don't know if my understanding is correct.

**Comment by tongji-rkr** [comment]
![image](https://github.com/city-super/Octree-GS/assets/93235593/50ebe24e-3973-4b9b-b634-bf9f4806aaa6)

**Comment by TSlus** [comment]
ok, thank you for your kind response to my question :)
