### ISSUE TITLE
Issues when training on MatrixCity

### ISSUE THREAD

**Issue by voidcf** [city-super/Octree-GS#34]
Hi, thanks for the great work. 
Lately I've been trying to reproduce your results with the MatrixCity dataset and so far have been unable to do so. In the paper, you have reported the results on MatrixCity for **block_small** & **block_all**, can you please give a little more detail on this. From what I understand (correct me if I am wrong), block_small is from the street scene and block_all from the aerial one?

**Comment by jianglh-WHU** [comment]
You can refer to MatrixCity, where both block_all and block_small represent aerial scenes. The main distinction between them lies in their respective sizes. Note: [Block_all](https://huggingface.co/datasets/BoDai/MatrixCity/tree/main/small_city/aerial/pose/block_all) and [Block_small](https://huggingface.co/datasets/BoDai/MatrixCity/tree/main/aerial_street_fusion)

**Comment by voidcf** [comment]
Okay, according to MatrixCity block_small is a part of the street_view data, whereas the one that you have linked here is a fusion of both street and aerial. Sorry I am a bit confused here...

**Comment by jianglh-WHU** [comment]
Indeed, block_small represents a specific region. Within this region, we gather both aerial and street images. For the Octree-GS experiment, we utilize the aerial images, while in the Figure 6 experiment of MatrixCity, we employ the street images.

**Comment by voidcf** [comment]
Oh okay, understood. Thanks a lot.
