### ISSUE TITLE
checkpoints for the Mip-NeRF 360, Tanks&Temples, Deep Blending and MatrixCity Dataset.

### ISSUE THREAD

**Issue by TSlus** [city-super/Octree-GS#36]
![oc](https://github.com/city-super/Octree-GS/assets/61425472/b83dccc4-fd51-47a2-b8ff-09ed703c5ded)
hello, Great job!  you said "[2024.05.30] 🎈We release the checkpoints for the Mip-NeRF 360, Tanks&Temples, Deep Blending and MatrixCity Dataset.", but i only find Mip-NeRF 360 checkpoints. Where is the MatrixCity  checkpoints ?

**Comment by TSlus** [comment]
![oc1](https://github.com/city-super/Octree-GS/assets/61425472/93ac0d14-51d9-4acd-8188-7d24e6924e73)
I only find Mip-NeRF 360 checkpoints.

**Comment by tongji-rkr** [comment]
![image](https://github.com/city-super/Octree-GS/assets/93235593/935355b2-7bbe-40bb-80fb-0cb08bee602e)
Please review README.
