### ISSUE TITLE
Evaluating on Synthetic-NeRF Dataset.

### ISSUE THREAD

**Issue by ZhiyeTang** [city-super/Octree-GS#40]
<img width="512" alt="image" src="https://github.com/user-attachments/assets/c486e2a9-b1e3-4a54-928e-2a6e16b193da">

The above lines from `scene\dataset_readers.py` seems incorrect. NeRF-Syntheticdataset did not provide any point clouds, so the used `glob` command is going to return a list with a length of 0, which will raise IndexError.

**Comment by ZhiyeTang** [comment]
Or have you built point clouds for NeRF-Synthetic scenes? If so, can you provide these point clouds? Or you were just using the random initialized point clouds like Scaffold-GS?

**Comment by tongji-rkr** [comment]
Thanks for your reminder, just use the random initialization after `lines 356`.
