### ISSUE TITLE
在运行bash train_mipnerf360.sh出现的问题

### ISSUE THREAD

**Issue by CBDXS1** [city-super/Octree-GS#41]
AttributeError: 'GaussianRasterizer' object has no attribute 'visible_filter'

Traceback (most recent call last):
  File "train.py", line 559, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), dataset,  args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, wandb, logger)
  File "train.py", line 141, in training
    voxel_visible_mask = prefilter_voxel(viewpoint_cam, gaussians, pipe, background)
  File "/home/zc107552403943/Octree-GS/gaussian_renderer/__init__.py", line 267, in prefilter_voxel
    radii_pure = rasterizer.visible_filter(means3D = means3D,
  File "/home/zc107552403943/anaconda3/envs/4dgs2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'GaussianRasterizer' object has no attribute 'visible_filter'
Training progress:   0%|                                                       | 0/40000 [00:00<?, ?it/s
不知道是不是版本的问题

**Comment by jianglh-WHU** [comment]
well, you need to recompile the [diff-gaussian-rasterization](https://github.com/city-super/Octree-GS/tree/main/submodules/diff-gaussian-rasterization).

**Comment by CBDXS1** [comment]
十分感谢十分感谢，我现在就试试

**Comment by KZI-22** [comment]
有用吗xd

**Comment by tongji-rkr** [comment]
https://github.com/tongji-rkr/diff-gaussian-rasterization
