### ISSUE TITLE
problem with train.sh

### ISSUE THREAD

**Issue by ferryman123** [city-super/Octree-GS#43]
When I tried to run the train.sh file, the following error occurred:

Traceback (most recent call last):
  File "train.py", line 561, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), dataset,  args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, wandb, logger)
  File "train.py", line 154, in training
    scaling_reg = scaling.prod(dim=1).mean()
   ...
extern "C"
__launch_bounds__(512, 4)
__global__ void reduction_prod_kernel(ReduceJitOp r){
  r.run();
}
nvrtc: error: invalid value for --gpu-architecture (-arch)

**Comment by jianglh-WHU** [comment]
please refer to https://github.com/city-super/Octree-GS/issues/7#issuecomment-2106538841
