### ISSUE TITLE
The 'core/view' of SIBR_viewer is missing

### ISSUE THREAD

**Issue by yzslab** [city-super/Octree-GS#5]
Hi, looks like the `core/view` is required but not included in this repository: https://github.com/city-super/Octree-GS/blob/0d4a97e79f93060d0d2be1dca0607f5b4fa32063/SIBR_viewers/src/CMakeLists.txt#L79

```bash
$ cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release
...
CMake Error at src/CMakeLists.txt:79 (add_subdirectory):
  add_subdirectory given source "core/view" which is not an existing
  directory.
...
```

**Comment by tongji-rkr** [comment]
Thanks for your reminder, we update the code.
