### ISSUE TITLE
Tips on large scenes

### ISSUE THREAD

**Issue by LaFeuilleMorte** [city-super/Octree-GS#51]
Hi, Thanks for open-source this brilliant work. I'm trying to reconstruct large scenes (> 1000 images with 8K resolution images). I was using Octree-GS to train on such large scenes But I found the metric (PSNR, Lpips) were converging really slow compared to smaller scenes. Any tips I can adopt to get better results?

**Comment by tongji-rkr** [comment]
Please show me your configs.

**Comment by LaFeuilleMorte** [comment]
> Please show me your configs.

Here's my config which was brrowed from train_matrixcity.sh:


scene="aerial_film_small_8K"
exp_name="aerial_film_small_8K"
gpu=-1
ratio=1
resolution=1
appearance_dim=0

fork=2
base_layer=10
visible_threshold=0.01
dist2level="round"
update_ratio=0.2

progressive="True"
dist_ratio=0.999 #0.99
levels=-1
init_level=-1
extra_ratio=0.25
extra_up=0.01

./train.sh -d ${scene} -l ${exp_name} --gpu ${gpu} -r ${resolution} --ratio ${ratio} --appearance_dim ${appearance_dim} \
   --fork ${fork} --visible_threshold ${visible_threshold} --base_layer ${base_layer} --dist2level ${dist2level} --update_ratio ${update_ratio} \
   --progressive ${progressive} --levels ${levels} --init_level ${init_level} --dist_ratio ${dist_ratio} \
   --extra_ratio ${extra_ratio} --extra_up ${extra_up}

**Comment by jianglh-WHU** [comment]
First, in large-scale scenes, we place the images in the CPU instead of CUDA to reduce GPU memory usage. If this method does not work, we recommend downsampling the image resolution.

**Comment by bzy-080408** [comment]
did you fixed it? and how many memory it cost when you put data to cpu-ram?

**Comment by LaFeuilleMorte** [comment]
> nes, we place the images in the CPU instead of CUDA to reduce GPU memory usage. If this method does not work, we recommend downsampling the image resolution.

Well, the memory comsuption is basically n* h *w *3 * 1 (bytes), where n is image nums, h, w are image size. As in my case, 1000 8K images usually took hundreds of GBs. So it's better not to load all datasets in RAM.
