### ISSUE TITLE
Support for gsplat as backend

### ISSUE THREAD

**Issue by LaFeuilleMorte** [city-super/Octree-GS#52]
Hi, thanks for your brilliant work. But I encountered big trouble when training large scenes with high resolution images (8K). Even 80 GB cuda memory was insufficient. Recently, A gaussian splatting cuda rasterizer was released (gsplat) which supports multi-gpu rasterization and significantly reduce memory usage.

**Comment by tongji-rkr** [comment]
refer to https://github.com/city-super/Octree-AnyGS

**Comment by tongji-rkr** [comment]
We recently added `gsplat` to our framework, refer to https://github.com/city-super/Octree-AnyGS.

**Comment by tongji-rkr** [comment]
DDP is not finished

**Comment by tongji-rkr** [comment]
We propose Octree-AnyGS, a general anchor-based framework that supports explicit Gaussians (2D-GS, 3D-GS) and neural Gaussians (Scaffold-GS). Additionally, Octree-GS has been adapted to the aforementioned Gaussian primitives, enabling Level-of-Detail representation for large-scale scenes. This framework holds potential for application to other Gaussian-based methods. Please refer to https://github.com/city-super/Octree-AnyGS.
