### ISSUE TITLE
How to conduct multi-resol training

### ISSUE THREAD

**Issue by renaissanceee** [city-super/Octree-GS#54]

**Comment by tongji-rkr** [comment]
Please set `self.resolution_scales`  as [1.0, 2.0, 4.0, 8.0].

**Comment by renaissanceee** [comment]
Thanks for your reply. However, I notice the description in paper 
> we multiply the observation distance with scaling factor accordingly to handle this multi-resolution dataset


e.g. 360_v2 with four downsampling scales. Where does the multiplication take place?
