### ISSUE TITLE
Possibility in integrating anti-aliasing method into Octree-GS

### ISSUE THREAD

**Issue by LaFeuilleMorte** [city-super/Octree-GS#56]
Hi, I observed there're some degrade when zoom in and zoom out in Octree-GS scenes. Is it possible to integrate mip-splatting or sa-gs filters into the Octree-GS. The octree-gs are generating gaussians on the fly. So I'm not sure if I can integrate the mip-splatting filter into current codebase.

**Comment by jianglh-WHU** [comment]
of course you can

**Comment by tongji-rkr** [comment]
Actually we take this problem into account and add `image_scale` in **LOD Level Selection** for regulation, but the qualitative effect is between Scaffel-GS and Mip-Splatting.
