### ISSUE TITLE
lr_max_steps

### ISSUE THREAD

**Issue by DuHao55** [city-super/Octree-GS#63]
I set the iterations in train.sh to 100_000 when training a large-scale scenario, and I noticed that self.iterations in __init__.py is 40_000, which results in lr_max_steps for position, offset, etc. also being 40_000. Should the self.iterations in arguments/__init__.py be set to the same as the iterations in train.sh?

**Comment by jianglh-WHU** [comment]
yes

**Comment by DuHao55** [comment]
Thanks for the prompt reply and looking forward to Block-Scaffold-GS & Octree-GS!
